/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSERVICES_H
#define _MOCKSERVICES_H

#include "services.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockservices_Init(void);
void Mockservices_Destroy(void);
void Mockservices_Verify(void);




#define time_now_ExpectAndReturn(cmock_retval) time_now_CMockExpectAndReturn(__LINE__, cmock_retval)
void time_now_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define tst_debugging_ExpectAndReturn(f, fi, l, e, cmock_retval) tst_debugging_CMockExpectAndReturn(__LINE__, f, fi, l, e, cmock_retval)
void tst_debugging_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* f, int fi, int l, char* e, uint8_t cmock_to_return);

#endif
